/*
 * Simple API
 *
 * A simple API to learn how to write OpenAPI Specification
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Article struct {

	Id int `json:"id"`

	ArticleContent string `json:"content"`

	Author string `json:"author"`

	Title string `json:"title"`

}
