/*
 * Simple API
 *
 * A simple API to learn how to write OpenAPI Specification
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/openapi101/",
		Index,
	},

	Route{
		"ArticleArticleIdGet",
		strings.ToUpper("Get"),
		"/openapi101/article/{article_id}",
		ArticleArticleIdGet,
	},

	Route{
		"ArticlePost",
		strings.ToUpper("Post"),
		"/openapi101/article",
		ArticlePost,
	},

	Route{
		"AuthSigninPost",
		strings.ToUpper("Post"),
		"/openapi101/auth/signin",
		AuthSigninPost,
	},

	Route{
		"AuthSignupPost",
		strings.ToUpper("Post"),
		"/openapi101/auth/signup",
		AuthSignupPost,
	},
}
